// Comprehensive bodyweight exercise database organized by muscle group
// Each exercise includes visual cues, minimal text instructions
// All images are unique — no recycled photos

export const muscleGroups = [
  { id: 'chest', label: 'Chest', emoji: '💪', color: 'from-red-500 to-rose-600', image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop' },
  { id: 'arms', label: 'Arms', emoji: '💪', color: 'from-orange-500 to-amber-600', image: 'https://images.unsplash.com/photo-1485727784872-0c3a4e7d4f1b?w=400&h=300&fit=crop' },
  { id: 'shoulders', label: 'Shoulders', emoji: '🏋️', color: 'from-yellow-500 to-orange-500', image: 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=400&h=300&fit=crop' },
  { id: 'back', label: 'Back', emoji: '🔙', color: 'from-emerald-500 to-green-600', image: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=400&h=300&fit=crop' },
  { id: 'core', label: 'Core', emoji: '🎯', color: 'from-cyan-500 to-blue-600', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop' },
  { id: 'legs', label: 'Legs', emoji: '🦵', color: 'from-purple-500 to-violet-600', image: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400&h=300&fit=crop' },
  { id: 'glutes', label: 'Glutes', emoji: '🍑', color: 'from-pink-500 to-rose-500', image: 'https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?w=400&h=300&fit=crop' },
  { id: 'fullbody', label: 'Full Body', emoji: '🔥', color: 'from-red-600 to-orange-500', image: 'https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=400&h=300&fit=crop' },
];

export const difficultyLevels = {
  beginner: { label: '⭐', color: 'bg-green-500/20 text-green-400' },
  intermediate: { label: '⭐⭐', color: 'bg-yellow-500/20 text-yellow-400' },
  advanced: { label: '⭐⭐⭐', color: 'bg-red-500/20 text-red-400' },
};

export const exercises = [
  // CHEST — 5 unique images
  {
    id: 'pushup-standard',
    name: 'Push-Up',
    group: 'chest',
    secondary: ['arms', 'core'],
    difficulty: 'beginner',
    calories: 7,
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&h=400&fit=crop',
    reps: '10-15',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🖐️', text: 'Hands shoulder-width apart' },
      { icon: '📏', text: 'Body straight like a plank' },
      { icon: '⬇️', text: 'Lower chest to floor' },
      { icon: '💨', text: 'Inhale down · Exhale up' },
    ],
    tips: 'Keep elbows at 45°. Don\'t let hips sag.',
  },
  {
    id: 'pushup-wide',
    name: 'Wide Push-Up',
    group: 'chest',
    secondary: ['shoulders'],
    difficulty: 'beginner',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&h=400&fit=crop',
    reps: '8-12',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🖐️', text: 'Hands wider than shoulders' },
      { icon: '📏', text: 'Core tight, back flat' },
      { icon: '⬇️', text: 'Lower slowly for 2 sec' },
      { icon: '💨', text: 'Inhale down · Exhale up' },
    ],
    tips: 'Targets outer chest. Go slow for best results.',
  },
  {
    id: 'pushup-diamond',
    name: 'Diamond Push-Up',
    group: 'chest',
    secondary: ['arms'],
    difficulty: 'intermediate',
    calories: 9,
    image: 'https://images.unsplash.com/photo-1574680178181-d2c75e10d0e3?w=600&h=400&fit=crop',
    reps: '8-12',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '💎', text: 'Hands form diamond shape' },
      { icon: '📏', text: 'Elbows close to body' },
      { icon: '⬇️', text: 'Lower chest to hands' },
      { icon: '💨', text: 'Inhale down · Exhale push' },
    ],
    tips: 'Great for triceps and inner chest.',
  },
  {
    id: 'pushup-decline',
    name: 'Decline Push-Up',
    group: 'chest',
    secondary: ['shoulders'],
    difficulty: 'intermediate',
    calories: 10,
    image: 'https://images.unsplash.com/photo-1616803689943-5601631c7fec?w=600&h=400&fit=crop',
    reps: '8-10',
    sets: 3,
    rest: 75,
    steps: [
      { icon: '🪑', text: 'Feet on chair or bench' },
      { icon: '📏', text: 'Arms straight, core tight' },
      { icon: '⬇️', text: 'Lower nose toward floor' },
      { icon: '💨', text: 'Inhale down · Exhale up' },
    ],
    tips: 'Targets upper chest. Higher feet = harder.',
  },
  {
    id: 'pushup-incline',
    name: 'Incline Push-Up',
    group: 'chest',
    secondary: ['arms'],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=600&h=400&fit=crop',
    reps: '12-20',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🪑', text: 'Hands on desk or wall' },
      { icon: '📏', text: 'Body in straight line' },
      { icon: '⬇️', text: 'Lower chest to surface' },
      { icon: '💨', text: 'Inhale in · Exhale push' },
    ],
    tips: 'Perfect for beginners. Great at work!',
  },

  // ARMS — 4 unique images
  {
    id: 'tricep-dip',
    name: 'Chair Dips',
    group: 'arms',
    secondary: ['chest', 'shoulders'],
    difficulty: 'beginner',
    calories: 6,
    image: 'https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=600&h=400&fit=crop',
    reps: '10-15',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🪑', text: 'Grip edge of chair behind' },
      { icon: '🦵', text: 'Legs bent or straight' },
      { icon: '⬇️', text: 'Lower until 90° elbows' },
      { icon: '💨', text: 'Inhale down · Exhale up' },
    ],
    tips: 'Don\'t go too deep — protect shoulders.',
  },
  {
    id: 'arm-circles',
    name: 'Arm Circles',
    group: 'arms',
    secondary: ['shoulders'],
    difficulty: 'beginner',
    calories: 3,
    image: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&h=400&fit=crop',
    reps: '30 sec each direction',
    sets: 3,
    rest: 30,
    steps: [
      { icon: '🦅', text: 'Arms out to sides' },
      { icon: '🔄', text: 'Small circles forward' },
      { icon: '🔁', text: 'Then reverse backward' },
      { icon: '💨', text: 'Breathe steadily' },
    ],
    tips: 'Increase circle size for more burn.',
  },
  {
    id: 'plank-shoulder-tap',
    name: 'Plank Shoulder Taps',
    group: 'arms',
    secondary: ['core'],
    difficulty: 'intermediate',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1577221084712-45b0445d2b00?w=600&h=400&fit=crop',
    reps: '20 taps',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🧱', text: 'Start in high plank' },
      { icon: '🖐️', text: 'Tap opposite shoulder' },
      { icon: '⚖️', text: 'Minimize hip sway' },
      { icon: '💨', text: 'Exhale on each tap' },
    ],
    tips: 'Wider feet = easier balance.',
  },
  {
    id: 'close-grip-pushup',
    name: 'Close Grip Push-Up',
    group: 'arms',
    secondary: ['chest'],
    difficulty: 'intermediate',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600&h=400&fit=crop',
    reps: '8-12',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🖐️', text: 'Hands close together' },
      { icon: '📏', text: 'Elbows tight to ribs' },
      { icon: '⬇️', text: 'Lower slowly' },
      { icon: '💨', text: 'Inhale down · Exhale push' },
    ],
    tips: 'Killer tricep builder.',
  },

  // SHOULDERS — 3 unique images
  {
    id: 'pike-pushup',
    name: 'Pike Push-Up',
    group: 'shoulders',
    secondary: ['arms'],
    difficulty: 'intermediate',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=600&h=400&fit=crop',
    reps: '8-12',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '⛰️', text: 'Hips high, inverted V' },
      { icon: '🖐️', text: 'Hands shoulder-width' },
      { icon: '⬇️', text: 'Lower head to floor' },
      { icon: '💨', text: 'Inhale down · Exhale push' },
    ],
    tips: 'Best bodyweight shoulder press!',
  },
  {
    id: 'wall-handstand-hold',
    name: 'Wall Handstand Hold',
    group: 'shoulders',
    secondary: ['core', 'arms'],
    difficulty: 'advanced',
    calories: 10,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop',
    reps: '20-30 sec hold',
    sets: 3,
    rest: 90,
    steps: [
      { icon: '🧱', text: 'Kick up against wall' },
      { icon: '📏', text: 'Arms locked, body tight' },
      { icon: '⏱️', text: 'Hold steady' },
      { icon: '💨', text: 'Short steady breaths' },
    ],
    tips: 'Builds serious shoulder strength.',
  },
  {
    id: 'lateral-raise-hold',
    name: 'Lateral Arm Hold',
    group: 'shoulders',
    secondary: ['arms'],
    difficulty: 'beginner',
    calories: 4,
    image: 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?w=600&h=400&fit=crop',
    reps: '30-45 sec hold',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🦅', text: 'Arms out at shoulder height' },
      { icon: '🖐️', text: 'Palms face down' },
      { icon: '⏱️', text: 'Hold — feel the burn' },
      { icon: '💨', text: 'Breathe steadily' },
    ],
    tips: 'Isometric burn — great at a desk!',
  },

  // BACK — 3 unique images
  {
    id: 'superman',
    name: 'Superman Hold',
    group: 'back',
    secondary: ['glutes'],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1606902965551-dce093cda6e7?w=600&h=400&fit=crop',
    reps: '10-15',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🛌', text: 'Lie face down' },
      { icon: '🦸', text: 'Lift arms and legs up' },
      { icon: '⏱️', text: 'Hold 2-3 seconds' },
      { icon: '💨', text: 'Inhale lift · Exhale lower' },
    ],
    tips: 'Squeeze shoulder blades together.',
  },
  {
    id: 'reverse-snow-angel',
    name: 'Reverse Snow Angel',
    group: 'back',
    secondary: ['shoulders'],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&h=400&fit=crop',
    reps: '10-12',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🛌', text: 'Lie face down, arms at sides' },
      { icon: '⬆️', text: 'Lift chest slightly' },
      { icon: '🔄', text: 'Sweep arms overhead' },
      { icon: '💨', text: 'Exhale as arms sweep up' },
    ],
    tips: 'Strengthens entire posterior chain.',
  },
  {
    id: 'doorway-row',
    name: 'Doorway Row',
    group: 'back',
    secondary: ['arms'],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600&h=400&fit=crop',
    reps: '10-15',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🚪', text: 'Grip doorframe edges' },
      { icon: '🦵', text: 'Lean back, arms straight' },
      { icon: '⬆️', text: 'Pull chest to door' },
      { icon: '💨', text: 'Exhale as you pull' },
    ],
    tips: 'Adjust foot position for difficulty.',
  },

  // CORE — 5 unique images
  {
    id: 'plank',
    name: 'Plank',
    group: 'core',
    secondary: ['shoulders'],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop',
    reps: '30-60 sec hold',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🧱', text: 'Forearms on floor' },
      { icon: '📏', text: 'Body straight head to heel' },
      { icon: '🎯', text: 'Tighten abs, squeeze glutes' },
      { icon: '💨', text: 'Breathe steadily throughout' },
    ],
    tips: 'The king of core exercises.',
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    group: 'core',
    secondary: [],
    difficulty: 'beginner',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1540474948573-6bf69fb7c7e0?w=600&h=400&fit=crop',
    reps: '20 per side',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🛌', text: 'Lie back, hands behind head' },
      { icon: '🦵', text: 'Bring knee to opposite elbow' },
      { icon: '🔄', text: 'Alternate sides smoothly' },
      { icon: '💨', text: 'Exhale on each twist' },
    ],
    tips: '#1 rated ab exercise by research.',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climbers',
    group: 'core',
    secondary: ['legs', 'fullbody'],
    difficulty: 'intermediate',
    calories: 12,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=400&fit=crop',
    reps: '30 sec',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🧱', text: 'Start in high plank' },
      { icon: '🦵', text: 'Drive knees to chest fast' },
      { icon: '🔄', text: 'Alternate rapidly' },
      { icon: '💨', text: 'Rhythmic breathing' },
    ],
    tips: 'Cardio + core in one move.',
  },
  {
    id: 'leg-raise',
    name: 'Leg Raises',
    group: 'core',
    secondary: [],
    difficulty: 'intermediate',
    calories: 6,
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b6?w=600&h=400&fit=crop',
    reps: '10-15',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🛌', text: 'Lie flat, hands under hips' },
      { icon: '🦵', text: 'Lift straight legs to 90°' },
      { icon: '⬇️', text: 'Lower slowly — don\'t touch floor' },
      { icon: '💨', text: 'Exhale up · Inhale down' },
    ],
    tips: 'Targets lower abs. Go slow!',
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    group: 'core',
    secondary: [],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1652363723073-523f382c4d26?w=600&h=400&fit=crop',
    reps: '10 per side',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🛌', text: 'Lie back, arms up, knees 90°' },
      { icon: '🦵', text: 'Extend opposite arm & leg' },
      { icon: '📏', text: 'Keep lower back pressed down' },
      { icon: '💨', text: 'Exhale as you extend' },
    ],
    tips: 'Safest core exercise for bad backs.',
  },

  // LEGS — 5 unique images
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    group: 'legs',
    secondary: ['glutes'],
    difficulty: 'beginner',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&h=400&fit=crop',
    reps: '15-20',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🦶', text: 'Feet shoulder-width' },
      { icon: '⬇️', text: 'Sit back, knees over toes' },
      { icon: '📏', text: 'Thighs parallel to floor' },
      { icon: '💨', text: 'Inhale down · Exhale up' },
    ],
    tips: 'The foundation of lower body strength.',
  },
  {
    id: 'lunge',
    name: 'Walking Lunges',
    group: 'legs',
    secondary: ['glutes'],
    difficulty: 'beginner',
    calories: 9,
    image: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=600&h=400&fit=crop',
    reps: '12 per leg',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🚶', text: 'Step forward big' },
      { icon: '⬇️', text: 'Back knee nearly touches floor' },
      { icon: '📏', text: 'Front knee at 90°' },
      { icon: '💨', text: 'Inhale step · Exhale push up' },
    ],
    tips: 'Great for balance and definition.',
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    group: 'legs',
    secondary: ['glutes'],
    difficulty: 'beginner',
    calories: 6,
    image: 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=600&h=400&fit=crop',
    reps: '30-60 sec hold',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🧱', text: 'Back flat against wall' },
      { icon: '🦵', text: 'Thighs parallel to floor' },
      { icon: '📏', text: 'Knees at 90°' },
      { icon: '💨', text: 'Breathe steadily throughout' },
    ],
    tips: 'Isometric leg destroyer. Try it!',
  },
  {
    id: 'pistol-squat',
    name: 'Pistol Squat',
    group: 'legs',
    secondary: ['core'],
    difficulty: 'advanced',
    calories: 12,
    image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&h=400&fit=crop',
    reps: '5-8 per leg',
    sets: 3,
    rest: 90,
    steps: [
      { icon: '🦶', text: 'Stand on one leg' },
      { icon: '🦵', text: 'Extend other leg forward' },
      { icon: '⬇️', text: 'Squat all the way down' },
      { icon: '💨', text: 'Inhale down · Exhale push up' },
    ],
    tips: 'Elite level move. Use support first.',
  },
  {
    id: 'calf-raise',
    name: 'Calf Raises',
    group: 'legs',
    secondary: [],
    difficulty: 'beginner',
    calories: 4,
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    reps: '20-30',
    sets: 3,
    rest: 30,
    steps: [
      { icon: '🦶', text: 'Stand on edge of step' },
      { icon: '⬆️', text: 'Rise high on toes' },
      { icon: '⬇️', text: 'Lower below step level' },
      { icon: '💨', text: 'Exhale up · Inhale down' },
    ],
    tips: 'Hold the top for 2 seconds.',
  },

  // GLUTES — 4 unique images
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    group: 'glutes',
    secondary: ['legs', 'core'],
    difficulty: 'beginner',
    calories: 6,
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=400&fit=crop',
    reps: '15-20',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🛌', text: 'Lie back, knees bent' },
      { icon: '🍑', text: 'Drive hips to ceiling' },
      { icon: '⏱️', text: 'Squeeze glutes 2 sec at top' },
      { icon: '💨', text: 'Exhale up · Inhale down' },
    ],
    tips: 'Top glute builder. Squeeze hard!',
  },
  {
    id: 'single-leg-bridge',
    name: 'Single Leg Bridge',
    group: 'glutes',
    secondary: ['core'],
    difficulty: 'intermediate',
    calories: 8,
    image: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=600&h=400&fit=crop',
    reps: '10 per leg',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🛌', text: 'Lie back, one leg raised' },
      { icon: '🍑', text: 'Push hips up with one leg' },
      { icon: '⏱️', text: 'Hold 1 sec at top' },
      { icon: '💨', text: 'Exhale up · Inhale down' },
    ],
    tips: 'Advanced bridge variation.',
  },
  {
    id: 'donkey-kick',
    name: 'Donkey Kicks',
    group: 'glutes',
    secondary: [],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=600&h=400&fit=crop',
    reps: '15 per leg',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🐕', text: 'On all fours' },
      { icon: '🦵', text: 'Kick one leg up, knee bent' },
      { icon: '🍑', text: 'Squeeze glute at top' },
      { icon: '💨', text: 'Exhale on kick up' },
    ],
    tips: 'Keep hips level. Don\'t arch back.',
  },
  {
    id: 'fire-hydrant',
    name: 'Fire Hydrants',
    group: 'glutes',
    secondary: [],
    difficulty: 'beginner',
    calories: 5,
    image: 'https://images.unsplash.com/photo-1535743686920-55e4145369b9?w=600&h=400&fit=crop',
    reps: '15 per leg',
    sets: 3,
    rest: 45,
    steps: [
      { icon: '🐕', text: 'On all fours' },
      { icon: '🦵', text: 'Lift knee out to side' },
      { icon: '⏱️', text: 'Hold 1 sec at top' },
      { icon: '💨', text: 'Exhale as you lift' },
    ],
    tips: 'Targets side glutes (abductors).',
  },

  // FULL BODY — 5 unique images
  {
    id: 'burpee',
    name: 'Burpees',
    group: 'fullbody',
    secondary: ['chest', 'legs', 'core'],
    difficulty: 'advanced',
    calories: 15,
    image: 'https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=600&h=400&fit=crop',
    reps: '8-12',
    sets: 3,
    rest: 90,
    steps: [
      { icon: '🧍', text: 'Stand tall' },
      { icon: '⬇️', text: 'Drop to push-up' },
      { icon: '💥', text: 'Push up, jump feet in' },
      { icon: '🦘', text: 'Jump up explosively' },
    ],
    tips: 'The ultimate calorie torcher!',
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jacks',
    group: 'fullbody',
    secondary: ['legs', 'shoulders'],
    difficulty: 'beginner',
    calories: 10,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&h=400&fit=crop',
    reps: '30 sec',
    sets: 3,
    rest: 30,
    steps: [
      { icon: '🧍', text: 'Stand feet together' },
      { icon: '🦘', text: 'Jump feet wide, arms up' },
      { icon: '🔄', text: 'Jump back together' },
      { icon: '💨', text: 'Rhythmic breathing' },
    ],
    tips: 'Great warm-up or cardio blast.',
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    group: 'fullbody',
    secondary: ['core', 'legs'],
    difficulty: 'beginner',
    calories: 12,
    image: 'https://images.unsplash.com/photo-1609899537878-49b90b80f90a?w=600&h=400&fit=crop',
    reps: '30 sec',
    sets: 3,
    rest: 30,
    steps: [
      { icon: '🧍', text: 'Stand tall' },
      { icon: '🦵', text: 'Drive knees to waist' },
      { icon: '🏃', text: 'Run in place fast' },
      { icon: '💨', text: 'Quick rhythmic breaths' },
    ],
    tips: 'Pump arms for extra burn.',
  },
  {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    group: 'fullbody',
    secondary: ['core', 'shoulders', 'legs'],
    difficulty: 'intermediate',
    calories: 10,
    image: 'https://images.unsplash.com/photo-1552308995-2baac1ad5490?w=600&h=400&fit=crop',
    reps: '30 sec',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '🐻', text: 'On all fours, knees hovering' },
      { icon: '🖐️', text: 'Move opposite hand & foot' },
      { icon: '📏', text: 'Keep back flat, hips low' },
      { icon: '💨', text: 'Steady breathing' },
    ],
    tips: 'Full body coordination builder.',
  },
  {
    id: 'squat-jump',
    name: 'Squat Jumps',
    group: 'fullbody',
    secondary: ['legs', 'glutes'],
    difficulty: 'intermediate',
    calories: 13,
    image: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&h=400&fit=crop',
    reps: '10-15',
    sets: 3,
    rest: 60,
    steps: [
      { icon: '⬇️', text: 'Squat deep' },
      { icon: '🦘', text: 'Explode up, jump high' },
      { icon: '🦶', text: 'Land softly, absorb impact' },
      { icon: '💨', text: 'Exhale on jump' },
    ],
    tips: 'Power + cardio. Land soft!',
  },
];

export function getExercisesByGroup(groupId) {
  return exercises.filter(e => e.group === groupId);
}

export function getExerciseById(id) {
  return exercises.find(e => e.id === id);
}